"""描述你的更改

Revision ID: 90b3ba8b8ad9
Revises: 
Create Date: 2024-12-08 00:06:33.408360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '90b3ba8b8ad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    op.drop_table('article')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False, comment='标题'),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='分组ID'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='markdown内容'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ctime', mysql.DATETIME(), nullable=False),
    sa.Column('utime', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='文章',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='文章',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('group',
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False, comment='分组名称'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ctime', mysql.DATETIME(), nullable=False),
    sa.Column('utime', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='文章分组',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='文章分组',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
